url: https://hakanu.github.io/wp
baseurl: ""

# Site settings
title: Wordpress Hunt
email: info@wordpresshunt.com
description: "The best place on earth to find beautiful Wordpress themes!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 99FF00 #fed136
  secondary: fbbe23 #fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: John Doe
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jane Doe
  pic: 3
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/wordpress_hunt
  - title: facebook
    url: http://facebook.com/wordpress.hunt

# Postal address (add as many lines as necessary)
address:
  - line: 32432 St.
  - line: Istanbul, Türkiye

# Build settings
markdown: kramdown
permalink: pretty

# {% include services.html %}
# {% include portfolio_grid.html %}
# {% include contact.html %}
# <!-- {% include about.html %} -->
# <!-- {% include team.html %} -->
# <!-- {% include clients.html %} -->
